# Generated by Django 2.2.3 on 2019-08-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190812_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item_total',
            new_name='price',
        ),
    ]
